### ISSUE TITLE
request for README

### ISSUE THREAD

**Issue by qzmfranklin** [jesseduffield/lazysession#1]
I'm a big fan of lazeXYZ tools. Been using lazygit and lazydocker for a few months by now.

Would be nice to know what's this is all about.

I built and used it already.

It seems to be enclosing the ssh session in some way:
<img width="1434" alt="Screen Shot 2020-02-07 at 12 42 58" src="https://user-images.githubusercontent.com/5695733/74001652-61f47c00-49a7-11ea-9d0c-19309e0b9479.png">

I also tried using it with `wget`. It just started a session to download the file. After wget completes, it also exits.

So, back to the original question: what's this about?

**Comment by jesseduffield** [comment]
apologies, I didnt realise anybody would have noticed that i made this haha. The plan is to allow for you to run any command (typically a remote connection to a rails console etc) and run it in a terminal emulator, but with the ability to type out a line into a buffer locally and then send the whole line to the remote host upon pressing enter.

I’m making this because I’m always tripping up on my words when typing in a slow ssh session given how bad the lag is when it comes to seeing my words typed out.

This project has a secondary purpose of expanding the functionality of my fork of the gocui library to just deal with terminal output better in general. In lazygit and lazydocker, we need to switch to a subprocess when doing something that might require user input, but id prefer to just render everything in the main panel instead. So I’m mostly using this project as a launching board for stuff like that, as well as another program called lazy<undisclosed>
